In [1]:
import pandas as pd

In [2]:
heart=pd.read_csv('heart.csv')

In [3]:
heart.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [4]:
heart.describe()

age     anaemia  creatinine_phosphokinase    diabetes  \
count  299.000000  299.000000                299.000000  299.000000   
mean    60.833893    0.431438                581.839465    0.418060   
std     11.894809    0.496107                970.287881    0.494067   
min     40.000000    0.000000                 23.000000    0.000000   
25%     51.000000    0.000000                116.500000    0.000000   
50%     60.000000    0.000000                250.000000    0.000000   
75%     70.000000    1.000000                582.000000    1.000000   
max     95.000000    1.000000               7861.000000    1.000000   

       ejection_fraction  high_blood_pressure      platelets  \
count         299.000000           299.000000     299.000000   
mean           38.083612             0.351171  263358.029264   
std            11.834841             0.478136   97804.236869   
min            14.000000             0.000000   25100.000000   
25%            30.000000             0.000000  212500.000000   
50%            38.000000             0.000000  262000.000000   
75%            45.000000             1.000000  303500.000000   
max            80.000000             1.000000  850000.000000   

       serum_creatinine  serum_sodium         sex    smoking        time  \
count         299.00000    299.000000  299.000000  299.00000  299.000000   
mean            1.39388    136.625418    0.648829    0.32107  130.260870   
std             1.03451      4.412477    0.478136    0.46767   77.614208   
min             0.50000    113.000000    0.000000    0.00000    4.000000   
25%             0.90000    134.000000    0.000000    0.00000   73.000000   
50%             1.10000    137.000000    1.000000    0.00000  115.000000   
75%             1.40000    140.000000    1.000000    1.00000  203.000000   
max             9.40000    148.000000    1.000000    1.00000  285.000000   

       DEATH_EVENT  
count    299.00000  
mean       0.32107  
std        0.46767  
min        0.00000  
25%        0.00000  
50%        0.00000  
75%        1.00000  
max        1.00000

In [5]:
heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    int64  
 2   creatinine_phosphokinase  299 non-null    int64  
 3   diabetes                  299 non-null    int64  
 4   ejection_fraction         299 non-null    int64  
 5   high_blood_pressure       299 non-null    int64  
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64  
 9   sex                       299 non-null    int64  
 10  smoking                   299 non-null    int64  
 11  time                      299 non-null    int64  
 12  DEATH_EVENT               299 non-null    int64  
dtypes: float64(3), int64(10)
memory usage: 30.4 KB


In [6]:
%matplotlib inline

In [7]:
import matplotlib.pyplot as plt

In [8]:
# heart.hist(bins=50, figsize=(20,15))

## Training Testing and Splitting

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
train_set,test_set=train_test_split(heart,test_size=0.2,random_state=42)

In [11]:
print(f"Number of the rows {len(train_set)} and Numer of the colums {len(test_set)}")

Number of the rows 239 and Numer of the colums 60


In [12]:
# so we have 239 traing data and 60 for testing which is small 

## Stratified Shuffle

In [13]:
from sklearn.model_selection import StratifiedShuffleSplit

In [14]:
split=StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for train_index ,test_index in split.split(heart,heart["sex"]):
    strat_train_set=heart.loc[train_index]
    strat_test_set=heart.loc[test_index]

In [15]:
# Now Lets see all the values is it goes ?? every colum

In [16]:
strat_train_set['sex'].value_counts()

1    155
0     84
Name: sex, dtype: int64

In [17]:
#Check for the train_set 

In [18]:
strat_test_set['sex'].value_counts()

1    39
0    21
Name: sex, dtype: int64

In [19]:
# so All Values goes Good

In [20]:
heart=strat_train_set.copy()

## For Coorelations

In [21]:
# seeing corr matrix you know what is this?

In [22]:
corr_matrix=heart.corr()

In [23]:
corr_matrix['DEATH_EVENT'].sort_values(ascending=False)

DEATH_EVENT                 1.000000
serum_creatinine            0.312182
age                         0.264195
creatinine_phosphokinase    0.056413
high_blood_pressure         0.055084
anaemia                     0.045505
diabetes                    0.026468
smoking                    -0.002477
sex                        -0.036331
platelets                  -0.046670
serum_sodium               -0.185592
ejection_fraction          -0.271493
time                       -0.552811
Name: DEATH_EVENT, dtype: float64

In [24]:
## Differnece the models

In [25]:
heart=strat_train_set.drop('DEATH_EVENT', axis=1)
heart_labels=strat_train_set['DEATH_EVENT'].copy()

## Creating Pipe Line

In [26]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [27]:
my_pipeline=Pipeline(
   [ ('std_scaler', StandardScaler())]
)

In [28]:
heart_num_tr=my_pipeline.fit_transform(heart)

In [29]:
heart_num_tr

array([[ 0.12647529,  1.11069566, -0.46962302, ...,  0.73616267,
        -0.69604026,  0.22208179],
       [-0.96710287,  1.11069566,  1.91474459, ..., -1.35839541,
        -0.69604026, -0.05117845],
       [-1.05122426, -0.90033664,  0.24935221, ...,  0.73616267,
         1.43669849, -0.97505827],
       ...,
       [-0.54649588,  1.11069566,  2.41058958, ...,  0.73616267,
        -0.69604026,  0.98981291],
       [-0.96710287,  1.11069566,  0.02622196, ..., -1.35839541,
        -0.69604026,  0.72956507],
       [-1.38770985, -0.90033664,  0.02622196, ..., -1.35839541,
        -0.69604026,  1.56235815]])

## Model Selection

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [31]:
# model=LogisticRegression()
# model=DecisionTreeRegressor()
model=RandomForestRegressor()
model.fit(heart_num_tr,heart_labels)

RandomForestRegressor()

In [32]:
## Comparing Our Data

In [33]:
some_data=heart.iloc[:5]

In [34]:
some_labels=heart_labels.iloc[:5]

In [35]:
predict_data=my_pipeline.transform(some_data)

In [36]:
model.predict(predict_data)

array([0.  , 0.6 , 0.99, 0.  , 0.6 ])

In [37]:
list(some_labels)

[0, 1, 1, 0, 1]

In [38]:
from sklearn.metrics import mean_squared_error
import numpy as np
heart_predictions=model.predict(heart_num_tr)
mse=mean_squared_error(heart_labels,heart_predictions)
rmse=np.sqrt(mse)

In [39]:
mse

0.016730543933054395

In [40]:
rmse

0.12934660387135952

## Cross Validation

In [41]:
from sklearn.model_selection import cross_val_score

In [42]:
scores=cross_val_score(model,heart_num_tr,heart_labels, scoring="neg_mean_squared_error", cv=10)
rmse_score=np.sqrt(-scores)

In [43]:
scores

array([-0.20884583, -0.12704583, -0.06575417, -0.19409583, -0.134425  ,
       -0.09590417, -0.08623333, -0.1289    , -0.11395   , -0.08026087])

In [44]:
rmse_score

array([0.45699654, 0.35643489, 0.25642575, 0.44056309, 0.36664015,
       0.30968398, 0.29365513, 0.35902646, 0.33756481, 0.28330349])

In [45]:
def print_scores(score):
    print("Number of Score",score)
    print("Mean is",score.mean())
    print("Standerd Deviation", score.std())

In [46]:
print_scores(scores)

Number of Score [-0.20884583 -0.12704583 -0.06575417 -0.19409583 -0.134425   -0.09590417
 -0.08623333 -0.1289     -0.11395    -0.08026087]
Mean is -0.12354150362318841
Standerd Deviation 0.04458081977132329


## Saveing File in JOB LiB

In [47]:
from joblib import dump,load
dump(model,"HeartFail.joblib")

['HeartFail.joblib']

## Testing The Model

In [48]:
X_test=strat_test_set.drop('DEATH_EVENT', axis=1)
Y_test=strat_test_set['DEATH_EVENT'].copy()
X_test_prediction=my_pipeline.transform(X_test)

In [49]:
final_predictions=model.predict(X_test_prediction)

In [50]:
final_mse=mean_squared_error(Y_test,final_predictions)
final_rse=np.sqrt(final_mse)

In [51]:
print("The MSE is" , final_mse)
print("The RMSE is", final_rse)

The MSE is 0.18293833333333334
The RMSE is 0.42771290994466526


In [52]:
X_test_prediction[1]

array([-0.29413169,  1.11069566, -0.16996018, -0.85550223,  0.12336784,
       -0.73616267, -0.96307216, -0.40464406,  0.51059118, -1.35839541,
       -0.69604026, -0.50661216])